### PR TITLE
feat: add rust-getrandom

### PR DESCRIPTION
**Pull request by Komorebi-yaodong**
Retrieve random data from system source.

Log: rust-getrandom src would be added.

Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/142

### CODE REVIEW

**Comment by chenchongbiao** [comment]
@chenchongbiao

**Comment by Komorebi-yaodong** [comment]
@chenchongbiao 麻烦老师检查一下这个PR

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
